<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Nullable>enable</Nullable>
		<Authors>Daniele Fusi</Authors>
		<Company>Fusi</Company>
		<Product>Cadmus</Product>
		<Description>Cadmus Itinera project services.</Description>
		<Copyright>By Daniele Fusi 2020</Copyright>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<PackageTags>Cadmus;itinera</PackageTags>
		<Version>9.0.3</Version>
		<FileVersion>9.0.3</FileVersion>
		<AssemblyVersion>9.0.3</AssemblyVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Cadmus.Core" Version="16.0.7" />
		<PackageReference Include="Cadmus.General.Parts" Version="16.0.7" />
		<PackageReference Include="Cadmus.Mongo" Version="16.0.7" />
		<PackageReference Include="Cadmus.Philology.Parts" Version="16.0.7" />
		<PackageReference Include="Cadmus.Seed.Codicology.Parts" Version="9.0.7" />
		<PackageReference Include="Cadmus.Seed.General.Parts" Version="16.0.7" />
		<PackageReference Include="Cadmus.Seed.Geo.Parts" Version="6.0.6" />
		<PackageReference Include="Cadmus.Seed.Philology.Parts" Version="16.0.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cadmus.Itinera.Parts\Cadmus.Itinera.Parts.csproj" />
		<ProjectReference Include="..\Cadmus.Seed.Itinera.Parts\Cadmus.Seed.Itinera.Parts.csproj" />
	</ItemGroup>

</Project>
